---
- logo:
    icon: mdi-flower-poppy

- greeting:
    text_size: xl
    text: BigHand Home

- resources:
    cpu: true
    memory: true
    disk: /

- search:
    provider: duckduckgo
    focus: true
    showSearchSuggestions: true
    target: _blank
